### ISSUE TITLE
check protected extensions method is not valid.

### ISSUE THREAD

**Issue by SeanBurt** [z0ccc/extension-detector#4]
<img width="821" alt="image" src="https://github.com/z0ccc/extension-detector/assets/18049638/c2e20503-1a13-42e2-8e2a-29ebcd569fde">
why use this url `chrome-extension://pmlfbbehleledmbphnielafhieceggal/${extension.file}` ? is have special mean?

**Comment by z0ccc** [comment]
The`testUrl` extension doesn't exist. I compare how quickly `url` loads in comparison to `testUrl`. If `url` has similar loading speeds to `testUrl` then `url` isn't installed. If `url`takes longer then it is installed.
